# Generated by Django 4.2.20 on 2025-04-22 19:19

from django.db import migrations, models
import django.db.models.deletion
import scout_services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scout_users', '0003_alter_user_address_alter_user_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_uuid', models.CharField(editable=False, max_length=255, unique=True)),
                ('years_of_experience', models.IntegerField()),
                ('service_description', models.TextField()),
                ('service_genre', models.CharField(choices=[('select', 'Select an option'), ('home_services', 'Home Services'), ('personal_care', 'Personal Care'), ('cleaning', 'Cleaning & Maintenance'), ('tech_support', 'Tech Support'), ('coaching_classes', 'Coaching & Classes'), ('vehicle_services', 'Vehicle Services'), ('home_improvement', 'Home Improvement')], default='select', max_length=255, verbose_name='genre')),
                ('fixed_price', models.DecimalField(decimal_places=2, help_text='10% of total fees  will be deducted as platfrom fee', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_images', models.ImageField(blank=True, null=True, upload_to=scout_services.models.ScoutServices.service_image_path)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='scout_users.serviceprovider', verbose_name='Service Provider')),
            ],
        ),
    ]
