# Generated by Django 4.2.20 on 2025-04-24 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scout_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoutservices',
            options={'verbose_name': 'Scout Service', 'verbose_name_plural': 'Scout Services'},
        ),
        migrations.AlterField(
            model_name='scoutservices',
            name='service_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
