# Generated by Django 4.2.20 on 2025-05-05 21:59

from django.db import migrations, models
import scout_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_users', '0004_alter_customer_options_alter_serviceprovider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=scout_users.models.User.photo_profile_path_location),
        ),
    ]
