# Generated by Django 4.2.20 on 2025-04-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout_bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='price',
        ),
    ]
