# Generated by Django 4.2.20 on 2025-04-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout_bookings', '0002_remove_servicebooking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='service',
            new_name='service_name',
        ),
    ]
