# Generated by Django 4.2.20 on 2025-04-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout_bookings', '0003_rename_service_servicebooking_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='service_provider',
        ),
    ]
